version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always