# Generated by Django 6.0.3 on 2026-04-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
