# Generated by Django 6.0.3 on 2026-04-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_task_due_date_task_is_completed_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_public',
        ),
    ]
