# Generated by Django 6.0.3 on 2026-04-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_boardinvitation_ownershiptransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_active',
        ),
        migrations.AddField(
            model_name='boardrole',
            name='can_manage_sprints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
