# Generated by Django 6.0.3 on 2026-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='token_hash',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
