name: Docker CD

on:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Restart Docker Containers
        run: |
          cd /home/ofeerist/Smart-Life-Manager

          git pull origin main

          sudo docker compose up -d --build
